fix(tracking): allow updating billed reports
adfinis-sygroup/timed-backend pull request #851
Opened 2022-02-22 09:07 UTC by trowik

updating billed reports should be allowed, as there are projects, that are billed in advance

2022-02-22 09:12 UTC, winged approved these changes
LGTM

2022-02-22 09:20 UTC, anehx approved these changes
Nice work!

2022-02-22 09:24 UTC, trowik commented
Complexity is too high :unamused: 
Any ideas on how to lower it? Or should I just increase the max-complexity for flake8?

2022-02-22 09:53 UTC, anehx commented
@trowik use the `validate_billed` method for validating this. You can use `validate_{field_name}` for all validations that are specific to one field only.

2022-02-23 12:23 UTC, trowik commented
re-requested review for the validate_billed change

2022-02-23 12:32 UTC, anehx requested changes
Otherwise LGTM :+1:

2022-02-23 12:32 UTC, anehx commented on timed/tracking/serializers.py
> +            if not user.is_accountant and (self.instance.billed != value):
```suggestion
            if not self.context["request"].user.is_accountant and (self.instance.billed != value):
```

2022-02-23 12:39 UTC, anehx approved these changes

2022-02-23 12:43 UTC, merged