feat(tracking): reject reports
adfinis-sygroup/timed-backend pull request #871
Opened 2022-07-19 12:07 UTC by trowik

reviewers can reject reports, if they were reported on the wrong task, project or customer
send mails when a report was rejected
only reviewer may reject reports
automatically un-reject reports when they were moved by the owner

2022-07-19 17:32 UTC, winged requested changes
Some minor things to clean up, otherwise LGTM, from an implementation perspective.

However, I think the feature is rather incomplete in it's current requirements. What we really want is to tell people not only *that* a report was rejected, but also (optionally) why, and how to correct it. Maybe we should think ahead a bit and add a `review_comment` field or something similar, to be filled and displayed where needed?

2022-07-19 17:32 UTC, winged commented on timed/tracking/models.py
> +        if instance.rejected:
```suggestion
    if instance.pk and instance.rejected:
```

2022-07-19 17:32 UTC, winged commented on timed/tracking/models.py
> +            if report.task != instance.task:
If you compare task_id instead of task, you get one or two DB queries less

2022-07-19 17:32 UTC, winged commented on timed/tracking/serializers.py
> +    rejected = serializers.BooleanField(required=False, allow_null=True)
Why allow_null? It's either True or False, no null reqired

2022-07-20 07:58 UTC, trowik commented
The comment on rejects isn't really necessary, as there are only two cases in which a report would be rejected. (Or at least I see only two cases):
1. The task, project or customer is wrong on the rejected report. In this case the reviewer won't exactly know which task/project/customer is correct, only that it shouldn't be reported on that specific task/project/customer. This would lead in most cases to a message similar to "Please change the task/project/customer. The report doesn't belong here."
2. The comment is inapproriate or not detailed (e.g. for customer visible reports). But this is rather an edge case and doesn't require the comment feature. (yet)
And if there really is a demand for a comment section after testing/release, we can still add it later on.

2022-07-29 14:23 UTC, winged approved these changes

2022-07-29 14:28 UTC, merged